pipeline {
    environment {
        MYSQL_ROOT_PASSWORD = credentials("MYSQL_ROOT_PASSWORD")
        DOCKER_HUB = credentials("DOCKERHUB_CREDENTIALS")
        APP_NAME = "flask app"
    }
    agent any
    stages {
        stage("Build MySQL") {
            steps {
                dir("Task2") {
                    sh "docker build -t trip-task-myswl:5.7 db"
                }
            }
        }
        stage("Build Flask App") {
            steps {
                dir("Task2") {
                    sh "docker build -t trio-task-flask-app:latest flask-app"
                }
            }
        }
        stage("Deploy Containers") {
            steps {
                dir("Task2") {
                    sh "sh deploy.sh"
                }
            }
        }
    }
}
        

