pipeline {
    environment {
        MYSQL_ROOT_PASSWORD = credentials("MYSQL_ROOT_PASSWORD")
        DOCKER_HUB = credentials("b16ef511-4cfd-4537-93b3-106656f2a519")
        APP_NAME = "flask app"
    }
    agent any
    stages {
        stage("Set up") {
            steps {
                dir("Task2") {
                    sh "sh deploy_set_up.sh"
                }
            }
        }
        stage("Create database") {
            steps {
                dir("Task2") {
                    sh "sh deploy_mysql.sh"
                }
            }
        }
        stage("Create flask app") {
            steps {
                dir("Task2") {
                    sh "sh deploy_flask.sh"
                }
            }
        }
        stage("Show containers") {
            steps {
                sh "docker ps -a"
                sh "docker images"
            }
        }
        stage("Push to DockerHub") {
            steps {
                sh 'docker push amckee457/$APP_NAME'
            }
        }
    }
    post {
        success {
            echo "success"
        }
    }
}

